name: Deploy to Lightsail

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tad-web:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Detener el contenedor actual
          docker stop tad-app || true
          docker rm tad-app || true
          
          # Descargar la nueva imagen
          docker pull ${{ secrets.DOCKER_USERNAME }}/tad-web:latest
          
          # Correr el nuevo contenedor
          # NOTA: Aquí inyectamos las variables de entorno reales del servidor
          docker run -d \
            --name tad-app \
            -p 80:8080 \
            --restart unless-stopped \
            --env-file .env \
            ${{ secrets.DOCKER_USERNAME }}/tad-web:latest