name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 1. Construir y Subir la imagen a Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/tad-web:latest

    # 2. Conectar a AWS e instalar Docker (si no existe) + Desplegar
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # 1. Crear el archivo .env en el servidor con el secreto
          # (Asegúrate de haber creado el secreto ENV_FILE en GitHub con todo el contenido de tu .env)
          echo "${{ secrets.ENV_FILE }}" > .env

          # 2. Limpieza
          docker stop tad-app || true
          docker rm tad-app || true
          
          # 3. Descargar imagen
          docker pull ${{ secrets.DOCKER_USERNAME }}/tad-web:latest
          
          # 4. Correr contenedor
          docker run -d \
            --name tad-app \
            -p 80:8080 \
            --restart unless-stopped \
            --env-file .env \
            ${{ secrets.DOCKER_USERNAME }}/tad-web:latest