export const disciplineOptions: string[] = [
    "Preliminary Works",
    "Structural Foundations",
    "Concrete Structure",
    "Metallic Structure",
    "Masonry Works",
    "Walls and Ceilings",
    "Aluminium works windows and glazing",
    "Blaksmithing",
    "Finishes",
    "Furniture",
    "Carpentry",
    "Mechanical",
    "Electrical",
    "Plumbing",
    "Fire Protection",
    "Special Systems",
    "HVAC",
    "Fire Alarm",
    "Security",
    "Access Control",
    "CCTV",
    "Data",
    "Telephony",
    "Audio Visual",
    "Low Voltage",
    "High Voltage",
    "Power",
    "Lighting",
    "For Reference Only",
  ];
  
  export const elementtype: string[] = [
    "Walls",
    "Doors",
    "Windows",
    "Roofs",
    "Floors",
    "Ceilings",
    "Stairs",
    "Railings",
    "Furniture",
    "Casework",
    "Curtain Walls",
    "Plumbin Fixtures",
    "Generic Models",
    "Topography",
    "Structural Columns",
    "Structural Conexions",
    "Structural Walls",
    "Structuaral Foundations",
    "Structural Framings",
    "Structural Trusses",
    "Structural Braces",
    "Structural Rebar",
    "Ducts",
    "Duct Fittings",
    "Duct Insulations",
    "Mechanical Equipment",
    "Air Terminals",
    "Flex Ducts",
    "Pipes",
    "Pipe Fittings",
    "Pipe Insulations",
    "Flex Pipes",
    "Pipe Accessories",
    "Conduit",
    "Conduit Fittings",
    "Cable Trays",
    "Cable Tray Fittings",
    "Light Fixtures",
    "Lighting Devices",
    "Fire Alarm Devices",
    "Electrical Devices",
    "Electrical Panels",
    "Electrical Equipment",
    "Electrical Fixtures",
    "Audio Visual Devices",
    "Communication Devices",
    "Data Devices",
    "Ramps",
    "Specialty Equipment",
    "Sprinklers",
  ];
  
  export interface IPropertyMapping {
    [key: string]: string;
  }
  
  export interface IPropertyMappingsCollection {
    "4D": IPropertyMapping;
    "5D": IPropertyMapping;
    "6D": IPropertyMapping;
    "7D": IPropertyMapping;
    [key: string]: IPropertyMapping; // Permitir otras dimensiones futuras
  }
  
  export const propertyMappings: IPropertyMappingsCollection = {
    "4D": {
      "Type Name": "TypeName",
      Description: "Description",
      Length: "Length",
      Width: "Width",
      Thickness: "Thickness",
      Height: "Height",
      Perimeter: "Perimeter",
      Area: "Area",
      Volume: "Volume",
      Level: "Level",
      Material: "Material",
      "Structural Material": "Material",
      "Reference Level": "Level",
      "Base Level": "Level",
      "Base Constraint": "Level",
      "Construction Start Date": "PlanedConstructionStartDate",
      "Construction End Date": "PlanedConstructionEndDate",
      "Construction Real Start Date": "RealConstructionStartDate",
      "Construction Real End Date": "RealConstructionEndDate",
    },
    "5D": {
      "Type Name": "TypeName",
      Description: "Description",
      "Type Mark": "TypeMark",
      Length: "Length",
      Width: "Width",
      Thickness: "Thickness",
      Height: "Height",
      Perimeter: "Perimeter",
      Area: "Area",
      Volume: "Volume",
      Level: "Level",
      Material: "Material",
      "Structural Material": "Material",
      "Reference Level": "Level",
      "Base Level": "Level",
      "Base Constraint": "Level",
      Unit: "Unit",
      Quantity: "Quantity",
      "Unit Price": "UnitPrice",
      "Total Cost": "TotalCost",
      Code: "Code",
    },
    "6D": {
      "Type Name": "TypeName",
      Description: "Description",
      "Type Mark": "TypeMark",
      Length: "Length",
      Width: "Width",
      Thickness: "Thickness",
      Height: "Height",
      Perimeter: "Perimeter",
      Area: "Area",
      Volume: "Volume",
      Level: "Level",
      Material: "Material",
      "Structural Material": "Material",
      "Reference Level": "Level",
      "Base Level": "Level",
      "Base Constraint": "Level",
      "Energy Consumption": "EnergyConsumption",
      "Carbon Footprint": "CarbonFootprint",
      "Life Cycle Stage": "LifeCycleStage",
      "LEED Category": "LEEDCategory",
      "LEED Credit": "LEEDCredit",
    },
    "7D": {
      "Type Name": "TypeName",
      Description: "Description",
      "Type Mark": "TypeMark",
      Length: "Length",
      Width: "Width",
      Thickness: "Thickness",
      Height: "Height",
      Perimeter: "Perimeter",
      Area: "Area",
      Volume: "Volume",
      Level: "Level",
      Material: "Material",
      "Structural Material": "Material",
      "Reference Level": "Level",
      "Base Level": "Level",
      "Base Constraint": "Level",
      "Energy Consumption": "EnergyConsumption",
      "Water Consumption": "WaterConsumption",
      "Carbon Footprint": "CarbonFootprint",
      Manufacturer: "Manufacturer",
      Model: "Model",
      Warranty: "Warranty",
      "Maintenance Period": "ManteinancePeriod",
      "Maintenance Cost": "ManteinanceCost",
      "Maintenance Date": "ManteinanceDate",
      "Serial Number": "SerialNumberId",
    },
  };
  
  export const numericFields: string[] = [
    "Length",
    "Width",
    "Height",
    "Perimeter",
    "Area",
    "Thickness",
    "Volume",
    "Cost",
    "EnergyConsumption",
    "CarbonFootprint",
  ];